//
//  NewMealWorker.swift
//  FoodListMJ
//
//  Created by Oleg Stepanov on 24.12.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase

class NewMealWorker {
    var ref: DatabaseReference = Database.database().reference()
    
    func firebaseWork(newMeal: MealSend) {
        let mealType = newMeal.type == .food ? "food" : "water"
        ref.child(mealType).childByAutoId().setValue(["Ch": false,
                                                      "Name": newMeal.name,
                                                      "Count": newMeal.count,
                                                      "Price": newMeal.price])
    }
}
