//
//  NewMealModels.swift
//  FoodListMJ
//
//  Created by Oleg Stepanov on 24.12.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum NewMeal {
    // MARK: Use cases
    
    enum AddMeal {
        struct Request {
            var newMeal: MealSend
        }
        
        struct Response {
            
        }
        
        struct ViewModel {
            
        }
    }
}
