//
//  NewMealPresenter.swift
//  FoodListMJ
//
//  Created by Oleg Stepanov on 24.12.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewMealPresentationLogic {
    func presentSomething(response: NewMeal.AddMeal.Response)
}

class NewMealPresenter: NewMealPresentationLogic {
    weak var viewController: NewMealDisplayLogic?

    // MARK: Parse and calc respnse from NewMealInteractor and send simple view model to NewMealViewController to be displayed

    func presentSomething(response: NewMeal.AddMeal.Response) {
        let viewModel = NewMeal.AddMeal.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
