//
//  NewMealRouter.swift
//  FoodListMJ
//
//  Created by Oleg Stepanov on 24.12.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol NewMealRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol NewMealDataPassing {
    var dataStore: NewMealDataStore? { get }
}

class NewMealRouter: NSObject, NewMealRoutingLogic, NewMealDataPassing {
    weak var viewController: NewMealViewController?
    var dataStore: NewMealDataStore?

// MARK: Routing (navigating to other screens)

//func routeToSomewhere(segue: UIStoryboardSegue?) {
//    if let segue = segue {
//        let destinationVC = segue.destination as! SomewhereViewController
//        var destinationDS = destinationVC.router!.dataStore!
//        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//    } else {
//        let storyboard = UIStoryboard(name: "Main", bundle: nil)
//        let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
//        var destinationDS = destinationVC.router!.dataStore!
//        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        navigateToSomewhere(source: viewController!, destination: destinationVC)
//    }
//}

// MARK: Navigation to other screen

//func navigateToSomewhere(source: NewMealViewController, destination: SomewhereViewController) {
//    source.show(destination, sender: nil)
//}

// MARK: Passing data to other screen

//    func passDataToSomewhere(source: NewMealDataStore, destination: inout SomewhereDataStore) {
//        destination.name = source.name
//    }
}
