//
//  NewMealInteractor.swift
//  FoodListMJ
//
//  Created by Oleg Stepanov on 24.12.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol NewMealBusinessLogic {
    func createNewMeal(request: NewMeal.AddMeal.Request)
//    func doSomethingElse(request: NewMeal.SomethingElse.Request)
}

protocol NewMealDataStore {
    //var name: String { get set }
}

class NewMealInteractor: NewMealBusinessLogic, NewMealDataStore {
    var presenter: NewMealPresentationLogic?
    var worker: NewMealWorker?
    //var name: String = ""

    // MARK: Do something (and send response to NewMealPresenter)

    func createNewMeal(request: NewMeal.AddMeal.Request) {
        worker = NewMealWorker()
        worker?.firebaseWork(newMeal: request.newMeal)

        let response = NewMeal.AddMeal.Response()
        presenter?.presentSomething(response: response)
    }
}
